

[[pages]]
path = "pagest/QA_chat.py"
name = "chat"
icon = ":books:"

[[pages]]
path = "pagest/KMS_embed.py"
name = "KMS"
icon = ":books:"

[[pages]]
path = ""
name = "Home"
icon = "ğŸ "
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
path = "pagest/Intro.py"
name = "ì¸íŠ¸ë¡œ"
icon = "ğŸ’ª"
